// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 21);
    lv_obj_set_x(ui_Button3, -86);
    lv_obj_set_y(ui_Button3, 126);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 20);
    lv_obj_set_x(ui_Button4, 85);
    lv_obj_set_y(ui_Button4, 127);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -86);
    lv_obj_set_y(ui_Label16, 128);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);

    ui_Label17 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -2);
    lv_obj_set_y(ui_Label17, -61);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);

    ui_Label18 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 84);
    lv_obj_set_y(ui_Label18, 128);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);

    ui_Button12 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button12, 100);
    lv_obj_set_height(ui_Button12, 50);
    lv_obj_set_x(ui_Button12, -2);
    lv_obj_set_y(ui_Button12, 78);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -2);
    lv_obj_set_y(ui_Label1, 78);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Button3 = NULL;
    ui_Button4 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    ui_Button12 = NULL;
    ui_Label1 = NULL;

}

void ui_Screen3_screen_relocalize(void)
{
    // label widgets on screen

}
