// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern void ui_Screen5_screen_relocalize(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

